# Generated by Django 3.2.7 on 2021-09-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('dirccion', models.CharField(max_length=256)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
    ]
