# Generated by Django 3.2.7 on 2021-09-26 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_sala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=256)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.sala')),
            ],
        ),
    ]
