# Generated by Django 3.2.7 on 2021-09-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0006_fila'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('fechaestreno', models.DateField()),
                ('preciotaquilla', models.CharField(max_length=10)),
            ],
        ),
    ]
